function Application(a){function b(a,b,c){pages&&pages[a]?b(pages[a]):jQuery.getScript("pages/"+a+".js",function(){b(pages[a])}).fail(function(a,b,f){c(f)})}function c(a){var b="Unknown";a&&(b=a.message||a.code||a.statusText);alert("Error: "+b);console.error(JSON.stringify(a))}var e=this,a=_.extend({localDb:!0,serverUrl:"http://data.mwater.co/mwater/apiv2/",cacheImages:!0,anchorState:!0,initialPage:"Main",initialPageArgs:[],requireLogin:!0,pageContainer:$("#page_container"),actionbar:void 0},a),d=
new SyncServer(a.serverUrl),f;if(a.localDb){var g=window.openDatabase("mwater","1.0","mWater",1E6);this.syncDb=new SyncDb(g,MWaterSqlModel.tableDefs);this.model=new MWaterSqlModel(g,this.syncDb);f=new SyncClient(this.syncDb,d)}else this.model=new MWaterApiModel(d);ProblemReporter.register(a.serverUrl,"0.30",function(){return d.getClientUid()});var h=new SourceCodeManager(d),k={canEdit:function(a){return a.created_by==d.getUsername()},canDelete:function(a){return a.created_by==d.getUsername()},canAdd:function(){return d.loggedIn()}},
l=a.cacheImages?new CachedImageManager(d,"Android/data/co.mwater.clientapp/images"):new SimpleImageManager(d);l.init(function(){e.model.init(function(){e.pager=new Pager(a.pageContainer,{model:e.model,template:e.createTemplate(),syncClient:f,syncServer:d,imageManager:l,sourceCodeManager:h,error:c,auth:k},a.actionbar);e.pager.onLoad=b;a.anchorState&&(e.pager.onStateChanged=function(a){window.location.href="#"+JSON.stringify(a)});window.device&&"Android"==window.device.platform&&document.addEventListener("backbutton",
function(){e.pager.closePage()},!1);a.requireLogin&&!d.loggedIn()?e.pager.loadPage("Login",[function(){e.pager.closePage(a.initialPage,a.initialPageArgs)}]):a.anchorState&&window.location.hash?e.pager.setState(JSON.parse(window.location.hash.substr(1))):e.pager.loadPage(a.initialPage,a.initialPageArgs);d.loggedIn()&&d.getWelcome("0.30",function(a,b,c){a?(b&&alert(b),c&&alert("Please exit application!")):(d.manualLogin("",""),e.pager.closePage("Login"))})},c)},c)}
Application.prototype.createTemplate=function(){dust.onLoad=function(a,c){$.get("templates/"+a+".html",null,function(a){c(null,a)},"text").error(function(a){c(a)})};var a=dust.makeBase({date:function(a,c,e,d){function f(a){return(10>a?"0":"")+a}c=new Date(1E3*d.value);return a.write(c.getFullYear()+"-"+f(c.getMonth()+1)+"-"+f(c.getDate()))},loc:function(a,c,e,d){return d.field?a.write(i18n.localizeField(d.field,d.value)):a}});return function(b,c,e){dust.render(b,a.push(c),function(a,b){a?error(a):
"function"==typeof e?e(b):e.html(b)})}};function GeoLoadTracker(){var a=[];this.reset=function(){a=[]};this.getNeeded=function(b){var c;_.each(a,function(a){if(a.rect.contains(b)&&(a.until||(c=null),void 0===c||null!==a.until&&a.until>c))c=a.until});return c?[{rect:b,since:c}]:null===c?[]:[{rect:b,since:null}]};this.recordLoaded=function(b,c){var e={rect:b,until:c||null};_.any(a,function(a){return a.rect.contains(e.rect)&&(!a.until||a.until>e.until)})||(a=_.filter(a,function(a){return!(e.rect.contains(a.rect)&&(!e.until||e.until>a.until))}),
a.push(e))}};var geoslicing=geoslicing||{};(function(){geoslicing.getSlices=function(a,b,c){function e(a){return(a+90+360)%180-90}function d(a){return(a+180+360)%360-180}var b=Math.round(b/a)*a,c=Math.round(c/a)*a,f=[];f.push([e(b-a),e(b),d(c-a),d(c)]);f.push([e(b),e(b+a),d(c-a),d(c)]);f.push([e(b-a),e(b),d(c),d(c+a)]);f.push([e(b),e(b+a),d(c),d(c+a)]);return _.map(f,function(a){return"source.rect:"+a.join()})}})();var HtmlActionbar=function(a,b){var b=_.extend({defaultTitle:"",fixedTop:!0},b||{}),c,e='<div class="navbar navbar-inverse'+(b.fixedTop?" navbar-fixed-top":'" style="position: relative')+'">',e=e+'<a class="btn btn-navbar dropdown-toggle pull-right" data-toggle="dropdown" id="navbar_dropdown_button"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a><ul class="dropdown-menu pull-right" id="navbar_items_dropdown" role="menu"></ul>',e=e+'<ul class="nav pull-right" id="navbar_items"></ul>',
e=e+'<div class="navbar-inner" style="text-align:center; padding-left:0px">',e=e+'<a class="btn-back pull-left" href="#">Back</a>',e=e+'<span class="brand" id="navbar_brand" style="float:none; color:white"><span id="navbar_title"></span></span></div></div>',d=$(e);a.prepend(d);b.fixedTop&&a.css("padding-top","40px");d.find(".btn-back").on("tap",function(){c&&c("home");return!1});$("a.dropdown-toggle, .dropdown-menu a").on("touchstart",function(a){a.stopPropagation()});this.menu=function(a,b){c=b;
d.find("#navbar_items").html("");d.find("#navbar_items_dropdown").html("");d.find("#navbar_dropdown_button").hide();_.each(a,function(a){if(a.ifRoom){var c=$('<li><a href="#">'+(a.icon?'<img height="20" width="20" src="'+a.icon+'">':a.title)+"</a></li>");c.click(function(){d.find('[data-toggle="dropdown"]').parent().removeClass("open");b(a.id);return!1});d.find("#navbar_items").append(c)}else c=$('<li><a href="#">'+(a.icon?'<img height="20" width="20" src="'+a.icon+'">':"")+a.title+"</a></li>"),c.on("tap",
function(){d.find('[data-toggle="dropdown"]').parent().removeClass("open");b(a.id);return!1}),d.find("#navbar_dropdown_button").show(),c.addClass("dropdown"),d.find("#navbar_items_dropdown").append(c)})};this.title=function(a){d.find("#navbar_title").text(a?a:b.defaultTitle)};this.up=function(a,c){a?(d.find(".btn-back").show(),d.find(".btn-back").text(c?c:b.defaultTitle).show()):d.find(".btn-back").hide()}};i18n={localizeField:function(a,b){var c=a+"."+b;return this[c]?i18n[c]:c},"sources.source_type.0":"Piped into dwelling","sources.source_type.1":"Piped into yard/plot","sources.source_type.2":"Public tap or standpipe","sources.source_type.3":"Tubewell","sources.source_type.4":"Borehole","sources.source_type.5":"Protected dug well","sources.source_type.6":"Protected spring","sources.source_type.7":"Rainwater catchment","sources.source_type.8":"Unprotected spring","sources.source_type.9":"Unprotected dug well",
"sources.source_type.10":"Cart with tank","sources.source_type.11":"Tanker-truck","sources.source_type.12":"Surface Water","sources.source_type.13":"Bottled Water","sources.source_type.14":"Public tank or basin","sources.source_type.15":"Supply network sampling point","tests.test_type.0":"Petrifilm E. coli","tests.test_type.1":"10mL Colilert","tests.test_type.2":"100mL E. coli","tests.test_type.3":"UNC Compartmentalized Bag","tests.test_type.4":"Chlorine","tests.test_type.5":"General Microbiology",
"tests.test_type.5.type.ecoli":"E. coli","tests.test_type.5.type.total_coliforms":"Total Coliforms","tests.test_type.5.type.thermotolerant_coliforms":"Thermotolerant Coliforms","tests.test_type.5.type.enterococci":"Enterococci","tests.test_type.5.type.heterotrophic_plate_count":"Heterotrophic Plate Count","tests.test_type.5.type.faecal_streptococci":"Faecal streptococci","tests.test_type.5.type.clostridium_perfringens":"Clostridium perfringens","source_notes.operational.null":"Unknown","source_notes.operational.0":"Broken",
"source_notes.operational.1":"Working","source_notes.operational.false":"Broken","source_notes.operational.true":"Working"};function CachedImageManager(a,b){function c(a,b,f,d){var e=b.split("/");1==e.length?a.getDirectory(e[0],{create:!0},f,d):a.getDirectory(e[0],{create:!0},function(a){c(a,e.slice(1).join("/"),f,d)},d)}function e(a,b,d,m,j,p){if(0==a.length)c(g.root,d,function(a){f.download(encodeURI(b),a.fullPath+"/"+m+".jpg",function(a){j(a.toURL())},p)},p);else{var v=_.first(a);console.log("checking in: "+v);c(g.root,v,function(c){c.getFile(m+".jpg",{},function(a){a=a.toURL();j(a)},function(c){c.code==FileError.NOT_FOUND_ERR?
e(_.rest(a),b,d,m,j,p):p(c)})},p)}}this.syncServer=a;this.cachePath=b;var d=this,f=new FileTransfer,g=null;this.getImageThumbnailUrl=function(b,c,f){console.log("displayImageThumbnail:"+b);e([this.cachePath+"/cached/thumbnail",this.cachePath+"/cached/original",this.cachePath+"/pending/original"],a.getImageThumbnailUrl(b),this.cachePath+"/cached/thumbnail",b,c,f)};this.getImageUrl=function(b,c,f){console.log("displayImage:"+b);e([this.cachePath+"/cached/original",this.cachePath+"/pending/original"],
a.getImageUrl(b),this.cachePath+"/cached/original",b,c,f)};this.addImage=function(a,b,f,e){g.root.getFile(a,null,function(a){c(g.root,d.cachePath+"/pending/original",function(c){console.log("Moving file to: "+c.fullPath+"/"+b+".jpg");a.moveTo(c,b+".jpg",f,e)},e)},e)};this.uploadImages=function(b,f,e){c(g.root,d.cachePath+"/pending/original",function(c){c.createReader().readEntries(function(c){0==c.length?f(0):(b(c.length,0),(new FileTransfer).upload(c[0].fullPath,encodeURI(a.getImageUrl(c[0].name.split(".")[0])),
function(){c[0].remove(function(){f(c.length-1)},e)},function(a){409==a.http_status?c[0].remove(function(){f(c.length-1)},e):e(a)},{fileKey:"image",params:{clientuid:a.getClientUid()}}))},e)},e)};this.init=function(a,b){window.requestFileSystem(LocalFileSystem.PERSISTENT,0,function(b){g=b;a()},b)}}function SimpleImageManager(a){this.init=function(a){a()};this.getImageThumbnailUrl=function(b,c){c(a.getImageThumbnailUrl(b))};this.getImageUrl=function(b,c){c(a.getImageUrl(b))}};function MapMarkerManager(a,b,c){function e(a){_.each(j,function(b){b(a)})}function d(){var d=a.getBounds();if(null!=d){var j=d;j.toSpan();for(var n=j.getSouthWest().lng(),d=j.getSouthWest().lat(),q=j.getNorthEast().lng(),j=j.getNorthEast().lat(),n=n+0.2*(n-q),d=d+0.2*(d-j),q=q+0.2*(q-n),j=j+0.2*(j-d),d=new google.maps.LatLngBounds(new google.maps.LatLng(d,n),new google.maps.LatLng(j,q)),n=0,t,q=0;q<k.length;q++){var j=k[q],r=h[j],u=d.contains(r.getPosition());u&&null==r.getMap()&&n<l?r.setMap(a):
(!u||n>=l)&&null!=r.getMap()&&r.setMap(null);u&&(n<l&&(t=j),n++)}d=new utils.Rect(d.getSouthWest().lng(),d.getSouthWest().lat(),d.getNorthEast().lng(),d.getNorthEast().lat());d=b.getNeeded(d);0==d.length?n>l?e("too_many"):e("completed"):(haveEnough=_.all(d,function(a){return void 0!==t&&null!=a.since&&a.since>t}),(haveEnough&=n>=l)?e("too_many"):0<m?e("loading"):_.each(d,function(a){m++;c(a,f,g)}))}}function f(a,c,f){m--;b.recordLoaded(a,c);_.each(f,function(a,b){h[b]||(h[b]=a)});k=_.keys(h).sort();
d()}function g(){m--}var h={},k=[],l=300,m=0;google.maps.event.addListener(a,"idle",d);var j=[];this.addListener=function(a){j.push(a)};this.removeListener=function(a){j=_.without(j,a)};this.reset=function(){for(i=0;i<k.length;i++)h[k[i]].setMap(null);h={};k=[]};this.updateMarkers=d};function MWaterApiModel(a){function b(b){return a.baseUrl+b+"?clientuid="+a.getClientUid()}function c(a){this.table=a}function e(a,b){for(var e=0;e<a.length;e++)_.extend(a[e],new c(b));return a}this.init=function(a){a()};this.transaction=function(a,b,c){var e={jqXhrs:[]};a(e);$.when.apply(window,e.jqXhrs).done(c).fail(b)};this.insertRow=function(a,c,e){a.jqXhrs.push($.ajax(b(c+"/"+e.uid),{type:"PUT",data:e}))};this.updateRow=function(a,c,e){a.jqXhrs.push($.ajax(b(c.table+"/"+c.uid),{type:"POST",data:e}))};
this.deleteRow=function(a,c){a.jqXhrs.push($.ajax(b(c.table+"/"+c.uid),{type:"DELETE"}))};this.queryNearbySources=function(a,c,g,h,k){console.log("Begin query");var l=a-1+","+(a+1),m=c-1+","+(c+1);$.get(b("sources"),{latitude:l,longitude:m},function(b){b=b.sources;b=_.sortBy(b,function(b){return(a-b.latitude)*(a-b.latitude)+(c-b.longitude)*(c-b.longitude)});g&&(b=_.filter(b,function(a){return a.name&&-1!=a.name.indexOf(g)||a.code&&-1!=a.code.indexOf(g)}));e(b,"sources");h(b)}).error(k)};this.queryUnlocatedSources=
function(a,c,g,h){$.get(b("sources"),{latitude:"null",created_by:a},function(a){a=a.sources;c&&(a=_.filter(a,function(a){return a.name&&-1!=a.name.indexOf(c)||a.code&&-1!=a.code.indexOf(c)}));e(a,"sources");g(a)}).error(h)};this.querySourceByUid=function(a,f,e){$.get(b("sources/"+a),function(a){f(_.extend(a,new c("sources")))}).error(e)};this.querySamplesAndTests=function(a,c,g){$.get(b("sources/"+a),{samples:"all"},function(a){c(e(a.samples,"samples"))}).error(g)};this.querySourceNotes=function(a,
c,g){$.get(b("sources/"+a+"/source_notes"),function(a){c(e(a.source_notes,"source_notes"))}).error(g)};this.querySourceNoteByUid=function(a,f,e){$.get(b("source_notes/"+a),function(a){f(_.extend(a,new c("source_notes")))}).error(e)};this.queryTests=function(a,c,g){$.get(b("tests"),{created_by:a},function(a){c(e(a.tests,"tests"))}).error(g)};this.queryTestByUid=function(a,f,e){$.get(b("tests/"+a),function(a){f(_.extend(a,new c("tests")))}).error(e)};this.sourceTypes=_.range(16)};function MWaterSqlModel(a,b){function c(a){this.table=a}function e(b,f,e,d){var g=[],g=g.concat(_.map(_.where(MWaterSqlModel.tableDefs,{name:"sources"})[0].cols,function(a){return"sources."+a+" AS sources__"+a})),g=g.concat(_.map(_.where(MWaterSqlModel.tableDefs,{name:"samples"})[0].cols,function(a){return"samples."+a+" AS samples__"+a})),g=g.concat(_.map(_.where(MWaterSqlModel.tableDefs,{name:"tests"})[0].cols,function(a){return"tests."+a+" AS tests__"+a})),p="SELECT "+g.join()+" FROM tests         \t\tLEFT OUTER JOIN samples ON tests.sample=samples.uid         \t\tLEFT OUTER JOIN sources ON samples.source=sources.uid         \t\tWHERE "+
b+" ORDER BY tests.started_on DESC";a.transaction(function(a){a.executeSql(p,f,function(a,b){for(var f=[],d=0;d<b.rows.length;d++){var h=b.rows.item(d),k=Object.create(new c("tests"));k.sample=Object.create(new c("samples"));k.sample.source=Object.create(new c("samples"));_.each(h,function(a,b){var c=b.split("__");"tests"==c[0]&&"sample"!=c[1]?k[c[1]]=a:"samples"==c[0]&&"source"!=c[1]?k.sample[c[1]]=a:"sources"==c[0]&&(k.sample.source[c[1]]=a)});f.push(k)}e(f)})},d)}var d=this;this.init=function(c,
f){a.transaction(function(a){d.createTables(a);b.createTables(a)},f,c)};this.reset=function(c,f){a.transaction(function(a){d.dropTables(a);b.dropTables(a);d.createTables(a);b.createTables(a)},f,c)};this.createTables=function(a){a.executeSql("CREATE TABLE IF NOT EXISTS sources(                       uid TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),                       row_version INTEGER DEFAULT 1,                       code TEXT,                       source_type INTEGER,                       name TEXT,                       desc TEXT,                       latitude REAL, longitude REAL,                       photo TEXT,                       created_by TEXT);");
a.executeSql("CREATE TABLE IF NOT EXISTS source_notes(                       uid TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),                       row_version INTEGER DEFAULT 1,                       source TEXT REFERENCES sources(uid) ON DELETE CASCADE,                       created_on INTEGER,                       operational INTEGER,                       note TEXT,                       created_by TEXT);");a.executeSql("CREATE TABLE IF NOT EXISTS samples(                       uid TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),                       row_version INTEGER DEFAULT 1,                       source TEXT REFERENCES sources(uid) ON DELETE CASCADE,                       code TEXT,                       desc TEXT,                       sampled_on INTEGER,                       created_by TEXT);");
a.executeSql("CREATE TABLE IF NOT EXISTS tests(                       uid TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),                       row_version INTEGER DEFAULT 1,                       sample TEXT REFERENCES samples(uid) ON DELETE CASCADE,                       test_type INTEGER NOT NULL,                       test_version INTEGER,                       code TEXT,                       started_on INTEGER,                       read_on INTEGER,                       dilution INTEGER DEFAULT 1,                       results TEXT,                       notes TEXT,                       photo TEXT,                       created_by TEXT);")};
this.dropTables=function(a){a.executeSql("DROP TABLE IF EXISTS sources;");a.executeSql("DROP TABLE IF EXISTS source_notes;");a.executeSql("DROP TABLE IF EXISTS samples;");a.executeSql("DROP TABLE IF EXISTS tests;")};this.transaction=function(b,c,f){a.transaction(b,c,f)};this.insertRow=function(a,c,f){a.executeSql("INSERT INTO "+c+" ("+_.keys(f).join()+") VALUES ("+_.map(f,function(){return"?"}).join()+");",_.values(f));b.recordInsert(a,c,f.uid)};this.updateRow=function(a,c,f){a.executeSql("UPDATE "+
c.table+" SET "+_.map(f,function(a,c){return c+"=?"}).join()+" WHERE uid=?",_.values(f).concat([c.uid]));b.recordUpdate(a,c.table,c.uid)};this.deleteRow=function(a,c){a.executeSql("DELETE FROM "+c.table+" WHERE uid=?",[c.uid]);b.recordDelete(a,c.table,c.uid)};var f=function(c,b,f,e,d){console.log("query: "+c+"error: "+typeof d);a.transaction(function(a){a.executeSql(c,b,function(a,c){for(var b=[],d=0;d<c.rows.length;d++){var k=Object.create(f);_.extend(k,c.rows.item(d));b.push(k)}e(b)})},d)},g=function(a,
c,b,e,d,g){f("SELECT * FROM "+a+" WHERE "+c+"=?",[b],e,function(a){0<a.length?d(a[0]):d(null)},g)};this.queryNearbySources=function(a,b,e,d,g){var p="SELECT * FROM sources WHERE latitude IS NOT NULL AND longitude IS NOT NULL"+(e?" AND (code LIKE ? OR name LIKE ? OR desc LIKE ?)":"")+" ORDER BY ((latitude-?)*(latitude-?)+(longitude-?)*(longitude-?))",a=[a,a,b,b];e&&a.unshift(e+"%",e+"%",e+"%");f(p,a,new c("sources"),d,g)};this.queryUnlocatedSources=function(a,b,e,d){var g="SELECT * FROM sources WHERE created_by = ? AND latitude IS NULL"+
(b?" AND (code LIKE ? OR name LIKE ? OR desc LIKE ?)":"")+" ORDER BY uid",a=[a];b&&a.push(b+"%",b+"%",b+"%");f(g,a,new c("sources"),e,d)};this.querySourceByUid=function(a,b,f){g("sources","uid",a,new c("sources"),b,f)};this.querySamplesAndTests=function(a,b,e){f("SELECT * FROM samples WHERE source=?",[a],new c("samples"),function(d){f("SELECT tests.* FROM tests INNER JOIN samples ON tests.sample=samples.uid WHERE samples.source=?",[a],new c("tests"),function(a){_.each(d,function(a){a.tests=[]});_.each(_.groupBy(a,
function(a){return a.sample}),function(a,b){_.find(d,function(a){return a.uid==b}).tests=a});b(d)},e)},e)};this.querySourceNotes=function(a,b,e){f("SELECT * FROM source_notes WHERE source=?",[a],new c("source_notes"),function(a){b(a)},e)};this.querySourceNoteByUid=function(a,b,f){g("source_notes","uid",a,new c("source_notes"),b,f)};this.queryTests=function(a,b,c){e("tests.created_by = ?",[a],b,c)};this.queryTestByUid=function(a,b,c){e("tests.uid = ?",[a],function(a){0<a.length?b(a[0]):b(null)},c)};
this.sourceTypes=_.range(16)}MWaterSqlModel.tableDefs=[{name:"sources",cols:"uid row_version code source_type name desc latitude longitude photo created_by".split(" ")},{name:"source_notes",cols:"uid row_version source created_on operational note created_by".split(" ")},{name:"samples",cols:"uid row_version source code desc sampled_on created_by".split(" ")},{name:"tests",cols:"uid row_version sample test_type test_version code started_on read_on dilution results notes photo created_by".split(" ")}];Pager=function(a,b,c){this.container=a;this.context=b;var e=this,d;a.on("mousedown touchstart","a,button,.tappable",function(){$(this).addClass("pressed");d=this});a.on("mouseup touchleave touchend touchmove touchcancel scroll",function(){d&&($(d).removeClass("pressed"),d=null)});a.on("tap",".checkbox",function(){$(this).toggleClass("checked");$(this).trigger("checked")});a.on("tap",".radio-button",function(){$(this).parents(".radio-group").find(".radio-button").removeClass("checked");$(this).addClass("checked");
$(this).trigger("checked")});a.on("click","a",function(){return!1});this.stack=[];this.state=[];this.activatePage=function(){var a=_.last(this.stack);c&&(c.menu(a.actionbarMenu||[],function(b){"home"==b?e.closePage():a.actionbarMenuClick&&a.actionbarMenuClick(b)}),a.actionbarTitle?c.title(a.actionbarTitle):c.title(null),c.up(1<this.stack.length,1<this.stack.length?this.stack[this.stack.length-2].actionbarTitle:null));a.activate&&a.activate()};this.onLoad=function(a,b,c){pages&&pages[a]?b(pages[a]):
c()};this.loadPage=function(c,d,h,k){console.log("Pager.loadPage("+c+", "+JSON.stringify(d)+")");this.onLoad(c,function(l){function m(){e.container.html("");e.container.append(j.$el);a.parent().scrollTop(0);e.activatePage(j)}!k&&0<e.stack.length&&(_.last(e.stack).deactivate&&_.last(e.stack).deactivate(),_.last(e.stack).$el.detach());var j=Object.create(l.prototype);l.apply(j,d);j.pager=e;_.extend(j,b);e.stack.push(j);e.state.push({name:c,args:d});e.onStateChanged(e.state);j.$el=$('<div id="page"></div>');
j.$=function(a){return j.$el.find(a)};j.create?j.create(function(){k||m();h&&h(j)}):k||(m(),h&&h(j))},function(a){console.error("Unable to load page. "+JSON.stringify(a));alert("Unable to load page. "+a)})};this.closePage=function(a,b){if(a||!(1>=this.stack.length)){if(0<this.stack.length){var c=this.stack.pop();this.state.pop();this.onStateChanged(e.state);c.deactivate&&c.deactivate();c.destroy&&c.destroy();c.$el.remove()}a?this.loadPage(a,b):0<this.stack.length&&(this.container.append(_.last(this.stack).$el),
this.activatePage())}};this.setState=function(a){1<a.length?this.loadPage(_.first(a).name,_.first(a).args,function(){e.setState(_.rest(a))},!0):0<a.length&&this.loadPage(a[0].name,a[0].args)};this.onStateChanged=function(){}};
Pager.makeTappable=function(a,b){a.on("tap","tr",function(){b(this)});var c;a.on("mousedown touchstart","tr",function(){$(this).addClass("pressed");c=this});a.on("mouseup touchleave touchend touchmove touchcancel mousemove scroll",function(){c&&($(c).removeClass("pressed"),_.delay(function(){$(c).removeClass("pressed");c=null},100))})};
Pager.makeSearchable=function(a,b){b.on("input change",function(){var b=this.value;a.find("tr").each(function(a){src=sources[a];-1==src.name.toLowerCase().indexOf(b.toLowerCase())?$(this).hide():$(this).show()})})};function PhotoDisplayer(a,b,c,e){function d(){c.photo?a.imageManager.getImageThumbnailUrl(c.photo,function(a){b.attr("src",a)},function(){b.attr("src","images/no-image-icon.jpg")}):b.attr("src","images/camera-icon.jpg")}d();b.on("tap",function(){if(c.photo)a.pager.loadPage("Photo",[c.photo]);else{var b=function(){console.error("Failed to take picture");alert("Failed to take picture")},g=function(b){console.log("Succeeded to take picture");var f=utils.createUid();a.imageManager.addImage(b,f,function(){a.model.transaction(function(b){a.model.updateRow(b,
c,{photo:f})},e,function(){c.photo=f;d()})},e)};navigator.camera?(console.log("About to take picture"),navigator.camera.getPicture(g,b,{quality:50,destinationType:Camera.DestinationType.FILE_URI})):alert("Camera not available")}})};function ProblemReporter(a,b,c){function e(a){var b=console[a];console[a]=function(a){d.push(a);200<d.length&&d.splice(0,20);b.call(console,a)}}var d=[],f=this;Function.prototype.bind&&(console&&"object"==typeof console.log)&&"log info warn error assert dir clear profile profileEnd".split(" ").forEach(function(a){console[a]=this.bind(console[a],console)},Function.prototype.call);e("log");e("warn");e("error");this.reportProblem=function(e){var f,g="";_.each(d,function(a){g+=String(a)+"\r\n"});f=g;
console.log("Reporting problem...");$.post(a+"problem_reports",{clientuid:c(),version:b,user_agent:navigator.userAgent,log:f,desc:e})};var g=_.debounce(this.reportProblem,5E3,!0),h=console.error;console.error=function(a){h(a);g(a)};window.onerror=function(a,b,c){f.reportProblem("window.onerror:"+a+":"+b+":"+c);alert("Internal Error\n"+a+"\n"+b+":"+c)}}
ProblemReporter.register=function(a,b,c){ProblemReporter.instances||(ProblemReporter.instances={});ProblemReporter.instances[a]||new ProblemReporter(a,b,c)};sampleanalysis={};
(function(){sampleanalysis.getAnalyses=function(a){analyses=[];anl=sampleanalysis.getEcoliAnalysis(a);null!=anl&&analyses.push(anl);return analyses};sampleanalysis.getEcoliAnalysis=function(a){var b=null,c=null;_.each(a.tests,function(a){if(a.results){var d=$.parseJSON(a.results),f=0;0==a.test_type?(f=null,d.autoEcoli&&(f=d.autoEcoli),d.manualEcoli&&(f=d.manualEcoli),range=null==f?{min:null,max:null}:{min:100*f*a.dilution,max:100*(f+1)*a.dilution}):range=1==a.test_type?!0==d.ecoli?{min:10*a.dilution,
max:null}:!1==d.ecoli?{min:null,max:10*a.dilution}:{min:null,max:null}:2==a.test_type?!0==d.ecoli?{min:a.dilution,max:null}:!1==d.ecoli?{min:null,max:a.dilution}:{min:null,max:null}:5==a.test_type&&"ecoli"==d.type?{min:a.dilution*d.value,max:a.dilution*d.value}:{min:null,max:null}}else range={min:null,max:null};if(null==b||range.min&&range.min>b)b=range.min;if(null==c||range.max&&range.max<c)c=range.max});return b||c?(anl={name:"E.Coli",namestyle:"font-style:italic;"},a=!1,b&&(c&&c<b+1)&&(c=b+1,a=
!0),anl.color=null==c?"#FF4040":1>=c?"#62B9FC":10>=c?"#40FF40":100>=c?"#FFFF40":1E3>=c?"#FFA040":"#FF4040",anl.risk=null==c?0:1>=c?1:10>=c?2:100>=c?3:1E3>=c?4:5,b&&c?anl.text=a?b+" CFU/100ml":c==b+1?b+" CFU/100ml":b+"-"+(c-1)+" CFU/100ml":c?anl.text="<"+c+" CFU/100ml":b&&(anl.text=">="+b+" CFU/100ml"),anl):null};sampleanalysis.summarizeTest=function(a){if(!a.results)return{text:"Pending"};var b=$.parseJSON(a.results),c=sampleanalysis.getEcoliAnalysis({tests:[a]});return 4==a.test_type?b.present?{text:"Positive",
color:"Green"}:{text:"Negative",color:"Red"}:5==a.test_type?{text:i18n.localizeField("tests.test_type.5.type",b.type)+": "+b.value+"/100mL",color:c?c.color:null}:c?{text:c.text,color:c.color}:{text:""}}})();function SourceCodeManager(a){function b(){return!localStorage.getItem("sourceCodes")?[]:JSON.parse(localStorage.getItem("sourceCodes"))}function c(a){localStorage.setItem("sourceCodes",JSON.stringify(a))}function e(a){c(_.reject(b(),function(b){return b.expiry<a}))}this.replenishCodes=function(d,f,g,h){h=h||(new Date).getTime()/1E3;e(h);d-=b().length;0>=d?f():a.requestSourceCodes(d,function(a,d){var e=_.map(a,function(a){return{code:a,expiry:(d-h)/2+h}});c(b().concat(e));f()},g)};this.getNumberAvailableCodes=
function(a){a=a||(new Date).getTime()/1E3;e(a);return b().length};this.requestCode=function(a,f,e){this.replenishCodes(1,function(){var f=b();c(_.rest(f));a(_.first(f).code)},f,e)};this.reset=function(){c([])}};function SourceMap(a,b,c,e){var d=this;this.updateMarkers=function(){this.geoLoadTracker.reset();this.mapMarkerManager.reset();this.mapMarkerManager.updateMarkers()};this.displayStatus=function(a){a?$("#status_control").text(a).show():$("#status_control").hide()};this.createMarker=function(a){var b;if(0<a.samples.length){b="#D0D0D0";var c=sampleanalysis.getAnalyses(_.last(a.samples));0<c.length&&(b=c[0].color)}else b="#D0D0D0";icon={path:google.maps.SymbolPath.CIRCLE,fillColor:b,fillOpacity:1,scale:6,
strokeColor:"black",strokeWeight:2};var d=new google.maps.Marker({position:new google.maps.LatLng(a.latitude,a.longitude),icon:icon});google.maps.event.addListener(d,"click",function(){e(a,d)});return d};c||(c={zoom:11,center:new google.maps.LatLng(-2.55,32.95),mapTypeId:google.maps.MapTypeId.ROADMAP});this.gmap=new google.maps.Map(a,c);d.gmap.controls[google.maps.ControlPosition.TOP_CENTER].push($('<div id="status_control" style="display:none;"></div>').get(0));d.geoLoadTracker=new GeoLoadTracker;
d.mapMarkerManager=new MapMarkerManager(d.gmap,d.geoLoadTracker,function(a,c){var e={limit:100,latitude:a.rect.y1+","+a.rect.y2,longitude:a.rect.x1+","+a.rect.x2,samples:1};a.since&&(e.uid_gt=a.since);$.get(b+"sources",e).success(function(b){var b=b.sources,e={};_.each(b,function(a){e[a.uid]=d.createMarker(a)});b=100<=b.length?_.last(b).uid:null;c(a.rect,b,e)}).error(function(){alert("Error getting data")})});d.mapMarkerManager.addListener(function(a){"completed"==a?d.displayStatus():"too_many"==
a?d.displayStatus("Zoom in to see more"):"loading"==a&&d.displayStatus("Loading...")})};SurveyModel=Backbone.Model.extend({});
Survey=Backbone.View.extend({className:"survey",template:_.template('<h2><%=title%></h2><ul class="breadcrumb"></ul><div class="sections"></div><button type="button" class="btn prev"><i class="icon-backward"></i> Back</button>&nbsp;<button type="button" class="btn btn-primary next">Next <i class="icon-forward icon-white"></i></button><button type="button" class="btn btn-primary finish">Finish</button>'),initialize:function(){this.title=this.options.title;this.sections=this.options.sections;this.render();
this.showSection(0)},events:{"tap .next":"nextSection","tap .prev":"prevSection","tap .finish":"finish","click a.section-crumb":"crumbSection"},finish:function(){if(this.sections[this.section].validate()&&this.options.onFinish)this.options.onFinish()},crumbSection:function(a){a=parseInt(a.target.getAttribute("data-value"));this.showSection(a)},nextSection:function(){this.sections[this.section].validate()&&this.showSection(this.section+1)},prevSection:function(){this.showSection(this.section-1)},showSection:function(a){this.section=
a;_.each(this.sections,function(a){a.$el.hide()});this.sections[a].$el.show();var b=_.first(this.sections,a+1);this.$(".breadcrumb").html(_.template('<% _.each(sections, function(s, i) { %> <li><a href="#" class="section-crumb" data-value="<%=i%>"><%=s.title%></a> <span class="divider">/</span></li> <% }); %>',{sections:_.initial(b)})+_.template('<li class="active"><%=title%></li>',_.last(b)));this.$(".prev").toggle(0<a);this.$(".next").toggle(a<this.sections.length-1);this.$(".finish").toggle(a==
this.sections.length-1)},render:function(){this.$el.html(this.template(this));var a=this.$(".sections");_.each(this.sections,function(b){a.append(b.$el)});return this}});
Section=Backbone.View.extend({className:"section",template:_.template('<h3><%=title%></h3><div class="contents"></div>'),initialize:function(){this.title=this.options.title;this.contents=this.options.contents;this.$el.hide();this.render()},validate:function(){var a=_.filter(this.contents,function(a){return a.visible&&a.validate});return!_.any(_.map(a,function(a){return a.validate()}))},render:function(){this.$el.html(this.template(this));var a=this.$(".contents");_.each(this.contents,function(b){a.append(b.$el)});
return this}});
Question=Backbone.View.extend({className:"question",template:_.template('<div class="prompt"><%=options.prompt%><%=renderRequired()%></div><div class="answer"></div>'),renderRequired:function(){return this.required?'&nbsp;<span class="required">*</span>':""},validate:function(){var a;if(this.required&&(void 0===this.model.get(this.id)||null===this.model.get(this.id)||""===this.model.get(this.id)))a="Required";!a&&this.options.validate&&(a=this.options.validate());a?this.$el.addClass("invalid"):this.$el.removeClass("invalid");
return a},updateVisibility:function(){this.shouldBeVisible()&&!this.visible&&this.$el.slideDown();!this.shouldBeVisible()&&this.visible&&this.$el.slideUp();this.visible=this.shouldBeVisible()},shouldBeVisible:function(){return!this.options.conditional?!0:this.options.conditional(this.model)},initialize:function(){this.model.on("change",this.updateVisibility,this);this.model.on("change:"+this.id,this.render,this);this.required=this.options.required;this.render()},render:function(){this.$el.html(this.template(this));
this.renderAnswer(this.$(".answer"));this.$el.toggle(this.shouldBeVisible());this.visible=this.shouldBeVisible();return this}});
RadioQuestion=Question.extend({events:{checked:"checked"},checked:function(a){a=parseInt(a.target.getAttribute("data-value"));this.model.set(this.id,this.options.options[a][0])},renderAnswer:function(a){a.html(_.template('<div class="radio-group"><%=renderRadioOptions()%></div>',this))},renderRadioOptions:function(){html="";var a;for(a=0;a<this.options.options.length;a++)html+=_.template('<div class="radio-button <%=checked%>" data-value="<%=position%>"><%=text%></div>',{position:a,text:this.options.options[a][1],
checked:this.model.get(this.id)===this.options.options[a][0]?"checked":""});return html}});
MulticheckQuestion=Question.extend({events:{checked:"checked"},checked:function(){var a=[],b=this.options.options;this.$(".checkbox").each(function(c){$(this).hasClass("checked")&&a.push(b[c][0])});this.model.set(this.id,a)},renderAnswer:function(a){var b;for(b=0;b<this.options.options.length;b++)a.append($(_.template('<div class="checkbox <%=checked%>" data-value="<%=position%>"><%=text%></div>',{position:b,text:this.options.options[b][1],checked:this.model.get(this.id)&&_.contains(this.model.get(this.id),
this.options.options[b][0])?"checked":""})))}});TextQuestion=Question.extend({renderAnswer:function(a){a.html(_.template('<input type="text"/>',this));a.find("input").val(this.model.get(this.id))},events:{change:"changed"},changed:function(){this.model.set(this.id,this.$("input").val())}});
NumberQuestion=Question.extend({renderAnswer:function(a){a.html(_.template('<input type="number"/>',this));a.find("input").val(this.model.get(this.id))},events:{change:"changed"},changed:function(){this.model.set(this.id,parseFloat(this.$("input").val()))}});PhotoQuestion=Question.extend({renderAnswer:function(a){a.html(_.template('<img style="max-width: 100px;" src="images/camera-icon.jpg"/>',this))},events:{"tap img":"takePicture"},takePicture:function(){alert("In an app, this would launch the camera activity as in mWater native apps.")}});
DateQuestion=Question.extend({events:{change:"changed"},changed:function(){this.model.set(this.id,this.$el.find('input[name="date"]').val())},renderAnswer:function(a){a.html(_.template('<input name="date" />',this));a.find("input").val(this.model.get(this.id));a.find("input").scroller({preset:"date",theme:"ios",display:"modal",mode:"scroller",dateOrder:"mmD ddyy"})}});function SyncClient(a,b){this.syncDb=a;this.syncServer=b}SyncClient.prototype.sync=function(a,b,c){var e=this;this.upload(function(d){e.syncDb.clearPendingChanges(d,function(){e.download(a,b,c)},c)},c)};SyncClient.prototype.download=function(a,b,c){var e=this;e.syncDb.getSliceUntils(a,function(d){e.syncServer.downloadChanges(d,function(d){e.applyChanges(d,a,b,c)},c)},c)};
SyncClient.prototype.upload=function(a,b){var c=this;this.syncDb.getPendingChanges(function(e){null!=e?c.syncServer.uploadChanges(e,function(){a&&a(e)},b):a&&a(null)},b)};SyncClient.prototype.applyChanges=function(a,b,c,e){var d=this;this.upload(function(f){f?d.applyChanges(a,b,c,e):d.syncDb.applyChanges(a,b,e,c)},e)};function SyncDb(a,b){this.db=a;this.tableDefs=b}SyncDb.prototype.createTables=function(a){a.executeSql("CREATE TABLE IF NOT EXISTS syncchanges (                   id INTEGER PRIMARY KEY AUTOINCREMENT,                   tablename TEXT NOT NULL,                   rowuid TEXT NOT NULL,                   action TEXT NOT NULL);");a.executeSql("CREATE TABLE IF NOT EXISTS dataslices (                   id TEXT PRIMARY KEY,                   serveruntil INTEGER NOT NULL);")};
SyncDb.prototype.dropTables=function(a){a.executeSql("DROP TABLE IF EXISTS syncchanges;");a.executeSql("DROP TABLE IF EXISTS dataslices;")};SyncDb.prototype.recordInsert=function(a,b,c){a.executeSql("INSERT INTO syncchanges (tablename, rowuid, action) VALUES (?, ?, ?);",[b,c,"I"])};SyncDb.prototype.recordUpdate=function(a,b,c){a.executeSql("INSERT INTO syncchanges (tablename, rowuid, action) VALUES (?, ?, ?);",[b,c,"U"])};
SyncDb.prototype.recordDelete=function(a,b,c){a.executeSql("INSERT INTO syncchanges (tablename, rowuid, action) VALUES (?, ?, ?);",[b,c,"D"])};
SyncDb.prototype.getPendingChanges=function(a,b){function c(a,b){var c=[],e;for(e=0;e<a;e++)c[e]=b;return c}function e(a){var b=[],c;for(c=0;c<a.rows.length;c++)b.push(a.rows.item(c));return b}function d(a,b,d){var f=_.find(g.tableDefs,function(a){return a.name==b.name});a.executeSql("SELECT * FROM "+b.name+" WHERE uid in ("+c(d.length,"?")+");",d,function(a,c){var d=e(c);0<d.length&&(b.upserts={cols:_.keys(_.pick(d[0],f.cols)),rows:[]},_.each(d,function(a){b.upserts.rows.push(_.values(_.pick(a,f.cols)))}))})}
function f(c,f){var l=_.groupBy(e(f),"tablename"),m={tables:[]};g.db.transaction(function(a){a.executeSql("SELECT MAX(id) AS until FROM syncchanges",[],function(a,b){m.until=b.rows.item(0).until||0});for(var b in l){_.find(g.tableDefs,function(a){return a.name==b});var c={name:b};m.tables.push(c);var e=_.pluck(_.where(l[b],{action:"I"}),"rowuid"),f=_.pluck(_.where(l[b],{action:"U"}),"rowuid"),h=_.pluck(_.where(l[b],{action:"D"}),"rowuid");0<h.length&&(c.deletes=h);e=_.difference(_.union(e,f),h);d(a,
c,e)}},b,function(){a(0<m.tables.length?m:null)})}var g=this;this.db.transaction(function(a){a.executeSql("SELECT * FROM syncchanges ORDER BY tablename, action, rowuid",[],f)},b)};SyncDb.prototype.clearPendingChanges=function(a,b,c){null!=a?this.db.transaction(function(b){b.executeSql("DELETE FROM syncchanges WHERE id<=?",[a.until])},c,b):b()};
SyncDb.prototype.getSliceUntils=function(a,b,c){this.db.transaction(function(e){e.executeSql("SELECT * FROM dataslices WHERE id IN ("+_.map(a,function(){return"?"}).join()+");",a,function(c,e){var g={},h;_.each(a,function(a){g[a]=0});for(h=0;h<e.rows.length;h++)g[e.rows.item(h).id]=e.rows.item(h).serveruntil;b(g)},c)})};
SyncDb.prototype.applyChanges=function(a,b,c,e){var d=this;a?this.db.transaction(function(c){_.each(b,function(b){c.executeSql("INSERT OR REPLACE INTO dataslices (id, serveruntil) VALUES (?,?);",[b,a.until])});_.each(a.tables,function(a){var b=_.find(d.tableDefs,function(b){return b.name==a.name});if(b){if(a.upserts){var e=a.upserts;_.each(e.rows,function(a){var d=_.object(e.cols,a),d=_.pick(d,b.cols),g=_.map(d,function(){return"?"}).join();c.executeSql("UPDATE "+b.name+" SET "+_.map(d,function(a,
b){return b+"=?"}).join()+" WHERE uid=?",_.values(d).concat([d.uid]),function(a,c){0==c.rowsAffected&&a.executeSql("INSERT INTO "+b.name+"("+_.keys(d).join()+") VALUES ("+g+");",_.values(d))})})}a.deletes&&_.each(a.deletes,function(a){c.executeSql("DELETE FROM "+b.name+" WHERE uid=?",[a])})}})},c,e):e()};function SyncServer(a){var b=this;this.baseUrl=a;this.manualLogin=function(a,b){localStorage.setItem("username",a);localStorage.setItem("clientUid",b)};this.signup=function(c,e,d,f,g){$.ajax(a+"users/"+e,{type:"PUT",data:{email:c,password:d}}).success(function(a){b.manualLogin(e,a.clientuid);f()}).error(g)};this.login=function(c,e,d,f){$.post(a+"users/"+c,{password:e}).success(function(a){b.manualLogin(c,a.clientuid);d()}).error(f)};this.logout=function(c,e){$.ajax(a+"clients/"+b.getClientUid(),{type:"DELETE",
success:c,error:e});b.manualLogin("","")};this.getUsername=function(){return localStorage.getItem("username")};this.getClientUid=function(){return localStorage.getItem("clientUid")};this.loggedIn=function(){return null!=this.getClientUid()&&""!=this.getClientUid()}}SyncServer.prototype.uploadChanges=function(a,b,c){$.post(this.baseUrl+"sync",{clientuid:this.getClientUid(),changeset:JSON.stringify(a)}).success(b).error(c)};
SyncServer.prototype.downloadChanges=function(a,b,c){$.get(this.baseUrl+"sync",{clientuid:this.getClientUid(),slices:JSON.stringify(a)}).success(function(a){b(a)}).error(c)};SyncServer.prototype.getImageThumbnailUrl=function(a){return this.baseUrl+"images/"+a+"/thumbnail"};SyncServer.prototype.getImageUrl=function(a){return this.baseUrl+"images/"+a};
SyncServer.prototype.requestSourceCodes=function(a,b,c){$.post(this.baseUrl+"source_codes",{clientuid:this.getClientUid(),number:a}).success(function(a){b(a.codes,a.expire_on)}).error(c)};SyncServer.prototype.getWelcome=function(a,b,c){$.get(this.baseUrl+"welcome/"+this.getClientUid(),{version:a},function(a){b(!0,a.message,a.fatal)}).error(function(a,d,f){403==a.status?b(!1,"",!1):c&&c(f)})};var utils=utils||{};
(function(){utils.createUid=function(){s="";var a;for(a=0;8>a;a++)s+=Math.floor(65536*Math.random()).toString(16);return s};utils.parseQuery=function(){var a={},b=window.location.search.replace("?","").split("&");$.each(b,function(b,e){var d=e.split("=");a[d[0]]=d[1]});return a};utils.Rect=function(a,b,c,e){this.x1=a;this.y1=b;this.x2=c;this.y2=e};utils.Rect.prototype.contains=function(a){return a.y1<this.y1||a.y2>this.y2?!1:this.x2>=this.x1?a.x1<=a.x2&&a.x1>=this.x1&&a.x2<=this.x2:a.x2>=a.x1?(a.x1>=
this.x1||a.x1<=this.x2)&&(a.x2<=this.x2||a.x2>=this.x1):a.x1>=this.x1&&a.x2<=this.x2};utils.Rect.prototype.pointWithin=function(a,b){return b<this.y1||b>this.y2?!1:this.x2>=this.x1?a>=this.x1&&a<=this.x2:a>=this.x1||a<=this.x2};utils.getRelativeLocation=function(a,b,c,e){e=6371E3*((e-b)/57.3);b=6371E3*(Math.cos(b/57.3)*(c-a)/57.3);a=Math.sqrt(b*b+e*e);e=90-57.3*Math.atan2(e,b);0>e&&(e+=360);360<e&&(e-=360);e=Math.floor((e+22.5)/45)%8;b="N NE E SE S SW W NW".split(" ");return 1E3<a?(a/1E3).toFixed(1)+
"km "+b[e]:a.toFixed(0)+"m "+b[e]};utils.isToday=function(a){return(new Date(a)).toLocaleDateString()==(new Date).toLocaleDateString()}})();(function(a){function b(a,b,c,d){var e=Math.abs(a-b),f=Math.abs(c-d);return e>=f?0<a-b?"Left":"Right":0<c-d?"Up":"Down"}function c(){l=null;f.last&&(f.el.trigger("longTap"),f={})}function e(){g&&clearTimeout(g);h&&clearTimeout(h);k&&clearTimeout(k);l&&clearTimeout(l);g=h=k=l=null;f={}}var d=!1;a(document).on("touchstart touchmove",function(){d=!0});a(document).on("mouseup",function(b){d||a(b.target).trigger("tap")});var f={},g,h,k,l;a(document).ready(function(){var d,j;a(document.body).bind("touchstart",
function(b){d=Date.now();j=d-(f.last||d);f.el=a("tagName"in b.originalEvent.touches[0].target?b.originalEvent.touches[0].target:b.originalEvent.touches[0].target.parentNode);g&&clearTimeout(g);f.x1=b.originalEvent.touches[0].pageX;f.y1=b.originalEvent.touches[0].pageY;0<j&&250>=j&&(f.isDoubleTap=!0);f.last=d;l=setTimeout(c,750)}).bind("touchmove",function(a){l&&clearTimeout(l);l=null;f.x2=a.originalEvent.touches[0].pageX;f.y2=a.originalEvent.touches[0].pageY}).bind("touchend",function(){l&&clearTimeout(l);
l=null;f.x2&&30<Math.abs(f.x1-f.x2)||f.y2&&30<Math.abs(f.y1-f.y2)?k=setTimeout(function(){f.el&&(f.el.trigger("swipe"),f.el.trigger("swipe"+b(f.x1,f.x2,f.y1,f.y2)));f={}},0):"last"in f&&(h=setTimeout(function(){var b=a.Event("tap");b.cancelTouch=e;f.el&&f.el.trigger(b);f.isDoubleTap?(f.el&&f.el.trigger("doubleTap"),f={}):g=setTimeout(function(){g=null;f.el&&f.el.trigger("singleTap");f={}},250)},0))}).bind("touchcancel",e);a(window).bind("scroll",e)});"swipe swipeLeft swipeRight swipeUp swipeDown doubleTap tap singleTap longTap".split(" ").forEach(function(b){a.fn[b]=
function(a){return this.bind(b,a)}})})(jQuery);var pages=pages||{};
pages.ExampleSurvey=function(){var a=this;this.create=function(b){this.template("example_survey",{},function(c){a.$el.html(c);a.surveyModel=new SurveyModel;a.surveyModel.on("change",function(){localStorage.setItem("examplesurvey",JSON.stringify(a.surveyModel.toJSON()))});var c=a.surveyModel,e=[],d=[];d.push(new RadioQuestion({id:"q1",model:c,required:!0,prompt:"Has post-installation water analysis EVER been completed for the site?",options:[[!0,"Yes"],[!1,"No"]]}));d.push(new DateQuestion({id:"q2",model:c,
required:!0,prompt:"When was the last water analysis completed?",conditional:function(a){return!0===a.get("q1")}}));d.push(new RadioQuestion({id:"q3",model:c,required:!0,prompt:"Are all of the water quality parameters below the threshold limits?",options:[[!0,"Yes"],[!1,"No"]],conditional:function(a){return!0===a.get("q1")}}));d.push(new MulticheckQuestion({id:"q4",model:c,prompt:"Which parameters exceed the limits?",options:[["tc","Total Coliforms"],["ecoli","E.Coli"],["turbidity","Turbidity"],["ph",
"pH"],["iron","Iron"],["other","Other"]],conditional:function(a){return!1===a.get("q3")&&!0===a.get("q1")}}));d.push(new NumberQuestion({id:"q5",model:c,prompt:"What is the concentration of Total Coliforms?",conditional:function(a){return!1===a.get("q3")&&a.get("q4")&&_.contains(a.get("q4"),"tc")&&!0===a.get("q1")}}));d.push(new NumberQuestion({id:"q6",model:c,prompt:"What is the concentration of E. Coli?",conditional:function(a){return!1===a.get("q3")&&a.get("q4")&&_.contains(a.get("q4"),"ecoli")&&
!0===a.get("q1")}}));d.push(new NumberQuestion({id:"q7",model:c,prompt:"What is the turbidity?",conditional:function(a){return!1===a.get("q3")&&a.get("q4")&&_.contains(a.get("q4"),"turbidity")&&!0===a.get("q1")}}));d.push(new NumberQuestion({id:"q8",model:c,prompt:"What is the pH?",conditional:function(a){return!1===a.get("q3")&&a.get("q4")&&_.contains(a.get("q4"),"ph")&&!0===a.get("q1")}}));d.push(new NumberQuestion({id:"q9",model:c,prompt:"What is the concentration of iron?",conditional:function(a){return!1===
a.get("q3")&&a.get("q4")&&_.contains(a.get("q4"),"iron")&&!0===a.get("q1")}}));e.push(section=new Section({title:"Water Quality",contents:d}));d=[];d.push(new RadioQuestion({id:"q10",model:c,prompt:"Is there a cover for the system?",options:[[!0,"Yes"],[!1,"No"]]}));d.push(new RadioQuestion({id:"q11",model:c,prompt:"Is there a lock and key for the cover?",options:[[!0,"Yes"],[!1,"No"]],conditional:function(a){return!0===a.get("q10")}}));d.push(new RadioQuestion({id:"q12",model:c,prompt:"Was the cover locked when you arrived on site?",
options:[[!0,"Yes"],[!1,"No"]],conditional:function(a){return!0===a.get("q10")&&!0===a.get("q11")}}));d.push(new RadioQuestion({id:"q13",model:c,prompt:"Is there ANY dust built up on the system?",options:[[!0,"Yes"],[!1,"No"]]}));d.push(new RadioQuestion({id:"q14",model:c,prompt:"Is there ANY grease collected on the system?",options:[[!0,"Yes"],[!1,"No"]]}));d.push(new PhotoQuestion({id:"q15",model:c,prompt:"Please take a picture of any dust or grease on the system.",conditional:function(a){return!0===
a.get("q13")||!0===a.get("q14")}}));e.push(section=new Section({title:"Water System",contents:d}));c=new Survey({title:"",sections:e,onFinish:function(){alert("Results recorded");a.pager.closePage()}});a.survey=c;a.$(".page").append(a.survey.$el);b()})};this.activate=function(){localStorage.getItem("examplesurvey")&&a.surveyModel.set(JSON.parse(localStorage.getItem("examplesurvey")))};this.deactivate=function(){localStorage.setItem("examplesurvey",JSON.stringify(a.surveyModel.toJSON()))};this.actionbarTitle=
"M&E Grading Survey";this.actionbarMenu=[{id:"reset",title:"Reset"}];this.actionbarMenuClick=function(b){"reset"==b&&confirm("Reset entire survey?")&&a.surveyModel.clear()}};pages=pages||{};
pages.Login=function(a){this.create=function(b){var c=this;this.template("login",null,function(e){c.$el.html(e);c.$("#login_button").on("tap",function(){c.$("#login_button").attr("disabled",!0);var b=c.$("#login_username").val(),e=c.$("#login_password").val();c.syncServer.login(b,e,function(){a?a(b):c.pager.closePage("Main")},function(){alert("Login failed");c.$("#login_button").attr("disabled",!1)});return!1});c.$("#signup_button").on("tap",function(){c.$("#signup_button").attr("disabled",!0);var b=
c.$("#signup_email").val(),e=c.$("#signup_username").val(),g=c.$("#signup_password").val();c.syncServer.signup(b,e,g,function(){a?a(e):c.pager.closePage("Main")},function(){alert("Signup failed");c.$("#signup_button").attr("disabled",!1)});return!1});b()})}};pages=pages||{};
pages.Main=function(){function a(){g=!1;f.$("#sync_error").hide();f.$("#sync_progress").hide();f.$("#sync_success").show().delay(2E3).slideUp()}function b(a){g=!1;var b=a.message||a.responseText||"Error connecting";console.warn("SyncError:"+JSON.stringify(a));f.$("#sync_progress").hide();f.$("#sync_success").hide();f.$("#sync_error").text("Unable to synchronize: "+b).show().delay(5E3).slideUp()}function c(){h?b("Cancelled"):f.imageManager.uploadImages?f.imageManager.uploadImages(function(a){f.$("#sync_progress_message").text("Uploading images. "+a+
" remaining.")},function(b){0<b?c():a()},function(a){b(a.http_status)}):a()}function e(a){slices=geoslicing.getSlices(1,a.coords.latitude,a.coords.longitude);slices.push("source.created_by:"+f.syncServer.getUsername());f.syncClient.sync(slices,c,function(a){b(a)})}function d(){f.syncClient&&!g&&(g=!0,h=!1,f.$("#sync_cancel").attr("disabled",!1),f.$("#sync_progress").show(),f.$("#sync_error").hide(),f.$("#sync_success").hide(),f.sourceCodeManager.replenishCodes(5,function(){navigator.geolocation.getCurrentPosition(e,
function(){b("Unable to get location")})},b))}var f=this;this.create=function(a){this.template("main",null,function(b){f.$el.html(b);f.$("#sources").on("tap",function(){f.pager.loadPage("Sources")});f.$("#map").on("tap",function(){f.pager.loadPage("Map")});f.$("#tests").on("tap",function(){f.pager.loadPage("Tests")});f.$("#settings").on("tap",function(){f.pager.loadPage("Settings")});f.$("#sync_cancel").on("tap",function(){h=!0;f.$("#sync_cancel").attr("disabled",!0)});a()})};this.activate=function(){"false"!=
localStorage.getItem("autoSync")&&d()};this.actionbarMenu=[{id:"sync",title:"Sync",icon:"images/sync.png",ifRoom:!0},{id:"logout",title:"Logout"}];this.actionbarTitle="mWater";var g=!1,h=!1;this.actionbarMenuClick=function(a){"sync"==a?d():"logout"==a?(a=function(){f.pager.closePage("Login")},this.syncServer.logout(a,a)):alert(a)}};pages=pages||{};
pages.Map=function(a){function b(a){f.syncClient?(d.displayStatus("Loading source..."),slices=["source.uid:"+a.uid],f.syncClient.sync(slices,function(){d.displayStatus();f.pager.loadPage("Source",[a.uid])},function(){d.displayStatus();alert("Unable to connect to server")})):f.pager.loadPage("Source",[a.uid])}function c(){function a(b){if(d){var c=new google.maps.LatLng(b.coords.latitude,b.coords.longitude);console.log("Got position: "+b.coords.latitude+","+b.coords.longitude);g.setPosition(c)}}function b(){}
navigator.geolocation&&!h&&(h=navigator.geolocation.watchPosition(a,b,{maximumAge:3E3,enableHighAccuracy:!0}))}function e(a){f.syncClient?f.syncClient.upload(a,f.error):a&&a()}var d,f=this,g,h,k=!0;this.create=function(h){this.template("map",null,function(k){f.$el.html(k);$.getScript("https://www.google.com/jsapi").done(function(){google.load("maps",3,{other_params:"sensor=true",callback:function(){e(function(){var e={zoom:13,center:a?new google.maps.LatLng(a.latitude,a.longitude):void 0,mapTypeId:google.maps.MapTypeId.ROADMAP};
d=new SourceMap($("#map_canvas").get(0),f.syncServer.baseUrl,e,b);a||navigator.geolocation.getCurrentPosition(function(a){d.gmap.setCenter(new google.maps.LatLng(a.coords.latitude,a.coords.longitude))});g=new google.maps.Marker({clickable:!1,icon:new google.maps.MarkerImage("images/my_location.png",new google.maps.Size(22,22),new google.maps.Point(0,0),new google.maps.Point(11,11)),shadow:null,zIndex:1E6,map:d.gmap});c()})}})});h()})};this.activate=function(){k||(c(),e(function(){d&&d.updateMarkers()}));
k=!1};this.deactivate=function(){h&&navigator.geolocation.clearWatch(h);h=null}};pages=pages||{};
pages.NewSource=function(a,b){var c=this;this.create=function(e){this.template("new_source",{sourceTypes:c.model.sourceTypes},function(d){c.$el.html(d);a&&c.$("#set_location").hide();c.$("#create_button").on("tap",function(){""==c.$("#source_type").val()?alert("Select source type"):c.sourceCodeManager.requestCode(function(d){uid=utils.createUid();source={uid:uid,code:d,name:c.$("#name").val(),desc:c.$("#desc").val(),source_type:parseInt(c.$("#source_type").val()),created_by:c.syncServer.getUsername()};a&&
_.extend(source,a);c.model.transaction(function(a){c.model.insertRow(a,"sources",source)},c.error,function(){b?b(uid):c.pager.closePage("Source",[uid,c.$("#set_location").hasClass("checked")])})},function(){alert("Unable to generate source id")})});c.$("#cancel_button").on("tap",function(){b?b():c.pager.closePage()});e()})}};pages=pages||{};
pages.NewTest=function(a){var b=this;this.create=function(c){this.template("new_test",{},function(e){b.$el.html(e);b.$("a").click(function(){var c=parseInt(this.id.substr(5)),e=function(a){uid=utils.createUid();test={uid:uid,test_type:c,test_version:1,sample:a,started_on:Math.floor((new Date).getTime()/1E3),created_by:b.syncServer.getUsername()};b.model.transaction(function(a){b.model.insertRow(a,"tests",test)},b.error,function(){b.pager.closePage("Test_"+c,[uid])})};a?b.model.querySamplesAndTests(a,function(c){if(0<
c.length&&utils.isToday(1E3*_.last(c).sampled_on))e(_.last(c).uid);else{var d=utils.createUid();sample={uid:d,source:a,sampled_on:Math.floor((new Date).getTime()/1E3),created_by:b.syncServer.getUsername()};b.model.transaction(function(a){b.model.insertRow(a,"samples",sample)},b.error,function(){e(d)})}},b.error):e(null);return!1});c()})}};pages=pages||{};pages.Photo=function(a){var b=this;this.create=function(c){this.template("photo",null,function(e){b.$el.html(e);b.imageManager.getImageUrl(a,function(a){b.$("#message_bar").hide();b.$("#image").attr("src",a).show()},b.error);c()})}};pages=pages||{};
pages.Settings=function(){function a(c){var e={offlineSourceCodes:b.sourceCodeManager.getNumberAvailableCodes(),username:b.syncServer.getUsername()};b.template("settings",e,function(d){b.$el.html(d);b.$("#auto_sync").toggleClass("checked","false"!=localStorage.getItem("autoSync"));b.$("#auto_sync").on("checked",function(){localStorage.setItem("autoSync",b.$("#auto_sync").hasClass("checked")?"true":"false")});b.$("#request_source_codes").on("tap",function(){b.sourceCodeManager.replenishCodes(e.offlineSourceCodes+5,
function(){a()},function(){alert("Unable to contact server")})});b.model instanceof MWaterSqlModel||b.$(".local_db_block").hide();b.$("#reset_database").on("tap",function(){confirm("Completely reset local database?")&&b.model.reset(function(){alert("Reset complete")},b.error)});c&&c()})}var b=this;this.create=a};pages=pages||{};
pages.Source=function(a,b,c){function e(){f&&(d.$("#location_map").attr("disabled",!f.latitude),b&&h?(b=!1,d.model.transaction(function(a){d.model.updateRow(a,f,{latitude:h.coords.latitude,longitude:h.coords.longitude})},d.error,function(){d.refresh()})):b?d.$("#location_relative").text("Setting location..."):f.latitude?h?d.$("#location_relative").text(utils.getRelativeLocation(h.coords.longitude,h.coords.latitude,f.longitude,f.latitude)):d.$("#location_relative").html('<img src="images/ajax-loader.gif"/>Waiting for GPS'):d.$("#location_relative").html("Unspecified location"))}
this.uid=a;var d=this,f,g,h;this.refresh=function(){this.model.querySourceByUid(this.uid,function(a){null==a?(alert("Source not found"),d.pager.closePage()):(f=a,d.template("source",f,function(a){d.$el.html(a);new PhotoDisplayer(d,d.$("#photo"),f,d.error);d.$("#location_set").on("tap",function(){confirm("Set to current location?")&&(b=!0,e())});d.$("#location_map").on("tap",function(){f.latitude&&d.pager.loadPage("Map",[{latitude:f.latitude,longitude:f.longitude}])});c&&d.$("#location").hide();d.$("#edit_source_button").on("tap",
function(){d.pager.loadPage("SourceEdit",[f.uid])});d.$("#add_test_button").on("tap",function(){d.pager.loadPage("NewTest",[f.uid])});d.$("#add_note_button").on("tap",function(){d.pager.loadPage("SourceNote",[f.uid])});Pager.makeTappable(d.$("#tests"),function(a){d.model.queryTestByUid(a.id,function(a){d.pager.loadPage("Test_"+a.test_type,[a.uid])},d.error)});Pager.makeTappable(d.$("#notes"),function(a){d.pager.loadPage("SourceNote",[f.uid,a.id])});d.auth.canEdit(f)||d.$("#edit_source_button, #location_set").attr("disabled",
!0);d.auth.canAdd("source_notes")||d.$("#add_note_button").attr("disabled",!0);d.auth.canAdd("samples")||d.$("#add_test_button").attr("disabled",!0);c||e();d.model.querySamplesAndTests(f.uid,function(a){var b={analyses:[]};_.each(a,function(a){_.each(sampleanalysis.getAnalyses(a),function(c){c.sample=a;b.analyses.push(c)})});d.template("source_analyses",b,$("#analyses"));b={tests:[]};_.each(a,function(a){_.each(a.tests,function(a){a.summary=sampleanalysis.summarizeTest(a);b.tests.push(a)})});d.template("source_tests",
b,$("#tests"))},d.error);d.model.querySourceNotes(f.uid,function(a){d.template("source_notes",{notes:a},$("#notes"))},d.error)}))},d.error)};this.activate=function(){function a(b){h=b;e()}function b(){}this.refresh();e&&(g=navigator.geolocation.watchPosition(a,b,{maximumAge:3E3,enableHighAccuracy:!0}))};this.deactivate=function(){e&&navigator.geolocation.clearWatch(g)};this.actionbarMenu=[{id:"delete",title:"Delete"}];this.actionbarTitle="Source";this.actionbarMenuClick=function(a){"delete"==a&&(d.auth.canDelete(f)?
confirm("Permanently delete source?")&&d.model.transaction(function(a){d.model.deleteRow(a,f)},d.error,function(){d.pager.closePage()}):alert("Insufficient permissions"))}};pages=pages||{};
pages.SourceEdit=function(a){var b=this;this.activate=function(){b.model.querySourceByUid(a,function(a){b.template("source_edit",{sourceTypes:b.model.sourceTypes},function(e){b.$el.html(e);b.$("#name").val(a.name);b.$("#desc").val(a.desc);b.$("#source_type").val(a.source_type);b.$("#save_button").on("tap",function(){update={name:b.$("#name").val(),desc:b.$("#desc").val(),source_type:parseInt(b.$("#source_type").val())};b.model.transaction(function(e){b.model.updateRow(e,a,update)},b.error,function(){b.pager.closePage()})});
b.$("#cancel_button").on("tap",function(){b.pager.closePage()})})},b.error)}};pages=pages||{};
pages.SourceNote=function(a,b){var c=this,e;this.activate=function(){function d(){c.template("source_note",e,function(d){c.$el.html(d);c.$("#note").val(e.note);c.$("#operational").val(e.operational);b&&!c.auth.canEdit(e)&&c.$("#save_button").attr("disabled",!0);c.$("#save_button").on("tap",function(){e.note=c.$("#note").val();e.operational=c.$("#operational").val();""===e.operational&&(e.operational=null);c.model.transaction(function(b){e.uid?c.model.updateRow(b,e,{note:e.note,operational:e.operational}):(e.uid=
utils.createUid(),e.created_on=Math.floor((new Date).getTime()/1E3),e.source=a,e.created_by=c.syncServer.getUsername(),c.model.insertRow(b,"source_notes",e))},c.error,function(){c.pager.closePage()})});c.$("#cancel_button").on("tap",function(){c.pager.closePage()})},c.error)}b?c.model.querySourceNoteByUid(b,function(a){e=a;d()},c.error):(e={},d())};this.actionbarMenu=[{id:"delete",title:"Delete"}];this.actionbarTitle="Source Note";this.actionbarMenuClick=function(a){var b=this;"delete"==a&&(e.uid||
b.pager.closePage(),b.auth.canDelete(e)?confirm("Permanently delete note?")&&b.model.transaction(function(a){b.model.deleteRow(a,e)},b.error,function(){b.pager.closePage()}):alert("Insufficient permissions"))}};pages=pages||{};
pages.Sources=function(){var a=this;this.create=function(b){this.template("sources",null,function(c){a.$el.html(c);Pager.makeTappable(a.$("#table"),function(b){a.pager.loadPage("Source",[b.id])});b()})};this.activate=function(){this.refresh("")};this.refresh=function(b){function c(b){a.$("#message_bar").hide();a.template("sources_rows",{rows:b},a.$("#table"))}function e(e){a.location=e;a.model.queryNearbySources(e.coords.latitude,e.coords.longitude,b,function(e){a.syncServer.loggedIn()?a.model.queryUnlocatedSources(a.syncServer.getUsername(),
b,function(a){c(e.concat(a))},a.error):c(e)},a.error)}function d(){alert("Unable to determine location")}a.location?e(a.location):(a.$("#message_text").text("Obtaining location..."),a.$("#message_bar").show(),navigator.geolocation.getCurrentPosition(e,d,{maximumAge:3600,timeout:1E4,enableHighAccuracy:!1}))};this.actionbarMenu=[{id:"new",title:"New",icon:"images/new.png",ifRoom:!0},{id:"search",title:"Search",icon:"images/search.png",ifRoom:!0}];this.actionbarTitle="Sources";this.actionbarMenuClick=
function(b){"search"==b?this.refresh(prompt("Search for:")):"new"==b?a.auth.canAdd("sources")?a.pager.loadPage("NewSource"):alert("Insufficient permissions"):alert(b)}};pages=pages||{};
pages.Test=function(){this.displayTest=function(){var a=this;new PhotoDisplayer(a,a.$("#photo"),a.test,a.error);a.auth.canEdit(a.test)||a.$("#edit_results_button, #record_results_button, #edit_notes_button").attr("disabled",!0);a.$("#edit_results_button, #record_results_button").on("tap",function(){a.$("#display_results").hide();a.$("#edit_results").show()});a.$("#save_results_button").on("tap",function(){var b=a.saveResults();if(b){var c={results:JSON.stringify(b)};a.test.read_on||(c.read_on=Math.floor((new Date).getTime()/
1E3));a.model.transaction(function(b){a.model.updateRow(b,a.test,c)},a.error,function(){a.refresh()})}});a.$("#cancel_results_button").on("tap",function(){a.$("#edit_results").hide();a.$("#display_results").show()});a.displayResults();a.$("#edit_notes_button").on("tap",function(){var b=prompt("Enter notes",a.test.notes);null!==b&&a.model.transaction(function(c){a.model.updateRow(c,a.test,{notes:b})},a.error,function(){a.refresh()})})};this.activate=function(){this.refresh()};this.createTemplateView=
function(a){return _.clone(a)};this.refresh=function(){var a=this;a.model.queryTestByUid(a.uid,function(b){null==b?(alert("Test not found"),a.pager.closePage()):(b.results&&(b.resultsData=JSON.parse(b.results)),a.test=b,a.template("test_"+b.test_type,a.createTemplateView(a.test),function(b){a.$el.html(b);a.displayTest()}))},a.error)};this.actionbarMenu=[{id:"delete",title:"Delete"}];this.actionbarTitle="Test";this.actionbarMenuClick=function(a){var b=this;"delete"==a&&(b.auth.canDelete(b.test)?confirm("Permanently delete test?")&&
b.model.transaction(function(a){b.model.deleteRow(a,b.test)},b.error,function(){b.pager.closePage()}):alert("Insufficient permissions"))}};pages=pages||{};
pages.Test_0=function(a){this.uid=a;var b=this;this.displayResults=function(){b.test.resultsData&&(b.$("input[name='ecoli']").val(b.test.resultsData.ecoli),b.$("input[name='tc']").val(b.test.resultsData.tc),b.$("input[name='other']").val(b.test.resultsData.other))};this.saveResults=function(){var a=_.pick(b.test.resultsData||{},"autoEcoli","autoTC","autoOther","autoAlgo");a.manualEcoli=parseInt($("input[name='ecoli']").val())||void 0;a.manualTC=parseInt($("input[name='tc']").val())||void 0;a.manualOther=
parseInt($("input[name='other']").val())||void 0;return a};this.createTemplateView=function(a){a=_.clone(a);if(a.resultsData){var b=a.resultsData;b.ecoli=b.manualEcoli||b.autoEcoli;b.tc=b.manualTC||b.autoTC;b.other=b.manualOther||b.autoOther}return a}};pages.Test_0.prototype=new pages.Test;pages.Test_0.prototype.constructor=pages.Test_0;pages=pages||{};pages.Test_1=function(a){this.uid=a;var b=this;this.displayResults=function(){b.test.resultsData&&(b.$("#blue_color").toggleClass("checked",!0==b.test.resultsData.ecoli),b.$("#yellow_color").toggleClass("checked",!0==b.test.resultsData.tc))};this.saveResults=function(){return{ecoli:$("#blue_color").hasClass("checked"),tc:$("#yellow_color").hasClass("checked")}}};pages.Test_1.prototype=new pages.Test;pages.Test_1.prototype.constructor=pages.Test_1;pages=pages||{};pages.Test_2=function(a){this.uid=a;var b=this;this.displayResults=function(){b.test.resultsData&&b.$("#bluegreen_color").toggleClass("checked",!0==b.test.resultsData.ecoli)};this.saveResults=function(){return{ecoli:$("#bluegreen_color").hasClass("checked")}}};pages.Test_2.prototype=new pages.Test;pages.Test_2.prototype.constructor=pages.Test_2;pages=pages||{};
pages.Test_4=function(a){this.uid=a;var b=this;this.displayResults=function(){b.test.resultsData?(b.$("#present").toggleClass("checked",!0==b.test.resultsData.present),$("#mgPerL").val(b.test.resultsData.mgPerL),b.test.resultsData.present||b.$("#chlorine_value").hide()):b.$("#chlorine_value").hide();b.$("#present").on("checked",function(){$("#present").hasClass("checked")?b.$("#chlorine_value").show():b.$("#chlorine_value").hide()})};this.saveResults=function(){var a={};a.present=$("#present").hasClass("checked");
if(a.present&&""!=$("#mgPerL").val()&&(a.mgPerL=parseFloat($("#mgPerL").val()),NaN==a.mgPerL)){alert("Invalid value");return}return a}};pages.Test_4.prototype=new pages.Test;pages.Test_4.prototype.constructor=pages.Test_4;pages=pages||{};
pages.Test_5=function(a){this.uid=a;var b=this;this.displayResults=function(){b.test.resultsData&&(b.$("#type").val(b.test.resultsData.type),b.$("#value").val(b.test.resultsData.value))};this.saveResults=function(){return{type:b.$("#type").val(),value:parseFloat(b.$("#value").val())}};this.createTemplateView=function(a){a=_.clone(a);a.types="ecoli total_coliforms thermotolerant_coliforms enterococci heterotrophic_plate_count faecal_streptococci clostridium_perfringens".split(" ");return a}};
pages.Test_5.prototype=new pages.Test;pages.Test_5.prototype.constructor=pages.Test_5;pages=pages||{};
pages.Tests=function(){var a=this;this.create=function(b){this.template("tests",null,function(c){a.$el.html(c);Pager.makeTappable(a.$("#table"),function(b){a.model.queryTestByUid(b.id,function(b){a.pager.loadPage("Test_"+b.test_type,[b.uid])},a.error)});b()})};this.activate=function(){this.refresh("")};this.refresh=function(){a.model.queryTests(a.syncServer.getUsername(),function(b){_.each(b,function(a){a.summary=sampleanalysis.summarizeTest(a)});a.template("tests_rows",{rows:b},a.$("#table"))},a.error)};
this.actionbarMenu=[{id:"new",title:"New",icon:"images/new.png",ifRoom:!0}];this.actionbarTitle="My Tests";this.actionbarMenuClick=function(a){"new"==a&&confirm("Create a test not associated with a source?")&&this.pager.loadPage("NewTest")}};
